### ISSUE TITLE
Can we reorganize this repo so that the file structure matches SEGS server?

### ISSUE THREAD

**Issue by broxen** [segs-community/cox-scripts#11]
## Summary
Can we reorganize this repo so that the file structure matches SEGS server, which would allow a user to download the entire repo and drop into their SEGS folder?

### Example
- :file_cabinet: cox-scripts repo root
  - :open_file_folder: DefaultMapInstances
    - :open_file_folder: City_00_01
      - :page_facing_up: entities.lua
      - :page_facing_up: locations.lua
      - :page_facing_up: plaques.lua
    - :open_file_folder: City_01_01
      - :page_facing_up: entities.lua
      - :page_facing_up: locations.lua
      - :page_facing_up: plaques.lua
    - :open_file_folder: City_02_01
    - *and so on...*

### Different Script-Packages
If this repo starts to hold different script packages `zophar-scripts` vs `broxen-scripts`, we can add an additional folder tier in the root for each package...
- :file_cabinet: cox-scripts repo root
  - :file_cabinet: zophar-scripts
    - :open_file_folder: DefaultMapInstances
      - :open_file_folder: City_00_01
  - :file_cabinet: broxen-scripts
    - :open_file_folder: DefaultMapInstances
      - :open_file_folder: City_00_01
      - *and so on...*

**Comment by segs-community** [comment]
I'm going to close this, but let's try to stick with this format moving forward.
