### ISSUE TITLE
Transcribe Power Data to a JSON file

### ISSUE THREAD

**Issue by cyanpill** [segs-community/cox-scripts#2]
Currently SEGS pulls powers.bin from the pigg files, but that data is incomplete. Specifically the data used for  "StoredAttribMod" [in this file](https://github.com/Segs/Segs/blob/develop/Projects/CoX/Common/GameData/power_definitions.h)

Possibility include:

- Getting a new source of data, maybe the fabled "city of data" files.

- Making a new file to be read alongside powers.bin, just having the missing data.

- Making a complete powers.json to replace powers.bin, which would great long term, but would be questionably legal. 

One useful tool would be some sort of a (web?) interface listing all the data, sortable, and editable so end users can make their own powers. There are existing ways to edit a JSON, but a custom tool could list off possible values, show things in a more user friendly way. For example "magnitude 5 name damage" becomes "causes 5 damage"

**Comment by cyanpill** [comment]
After some reseasch:

- getting an alternate powers.bin isn't feasible, would require rewriting the bitstream code to read the newer format, and we would be stuck with whatever is in the file.
- A parallel file with just the effect data might be viable, but would require the same format as a powers.json so it would be a lot of redundant work. Both would require either changing how archives are read, or adding a new function to read json/whatever data.

I'm heavily leaning towards json, since we already have a file mostly written, and it would have greater long term potential. 

I was hopping there would be someway to get a dump of newer power data, but it looks like we are going to have to enter everything by hand. With a decent UI, we could throw it to the users to crowdsource the data.

One tool I found that could be useful for getting newer power data is https://github.com/ovekaaven/cohtools which unfortunately lists all the variable names as "unknown" but the python code can be edited to add names. The output is plaintext, but maybe could be reformatted with a script. I don't know any python so I'm going to leave that alone for now.

**Comment by Baaleos** [comment]
I am going to have a go at writing a program to transcribe power entries from the full I24 Primary, Secondary, Ancillary powersets located here:
https://ipfs.infura.io/ipfs/QmcZJWh3fYjr1w5kJc13DLpBR4dnuFFBXHeG5RYdSPqYK9

To a format that resembles what you have started - however- When I put the one you have started through a JSON validator- it does not validate.
Coming from a .Net C# background - I use JSON2CSharp.com quite alot.
Would you be able to fix the json structure and then I will have a go at getting a transposition program running.
Cheers

**Comment by cyanpill** [comment]
My sample (https://github.com/segs-community/cox-scripts/blob/master/powers.json) was ripped out from the middle of a longer JSON, so a lot of formatting got left behind. This is the first JSON I've ever worked with :smile: I'll try to smooth it out.
