### ISSUE TITLE
Debugging Output and Dialog box for every entity

### ISSUE THREAD

**Issue by broxen** [segs-community/cox-scripts#5]
Zophar, these Outbreak scripts are great! I wanted to create this issue to track my feedback after using them briefly.

The scripts still contain a lot of apparent testing code. I discussed some of this briefly in discord.
- The code to fire Officer Flint's quest is commented out, so it'll never fire.
- There are logging outputs throughout the code -- Zophar and I talked about running these through a new logging category `logScripts` or something, which would resolve this issue
- Clicking on any entity (NPC, or Player, etc, doesn't matter) pops up a dialog box with their Entity ID, which is useful for testing, but creates unexpected client behavior for a user running the scripts and expecting the outbreak mission.
- As discussed in discord, the IDs of plaques appear to be different on my server. Because of this, none of the plaques fire. I'm not sure what could cause this, but perhaps switching to a loc-based, or name-based (or combo of both) identifier would be more definitive.

**Comment by segs-community** [comment]
PR #4 corrects the commented out code for Officer Flint.

**Comment by ZopharShinta** [comment]
I'll try to get the scripts to walk all of the way through the outbreak mission till we get to combat and update the scripts here.
That way we will have a "complete" script for anyone that wants to test with.

I might add another document here with all the functions thus far. Signatures, variables, etc.
So if someone wants to tweak them or mess around they'll have the details.

**Comment by segs-community** [comment]
We can add that documentation to the Wiki for this repo.

**Comment by segs-community** [comment]
I'm closing this. Looks like Zophar fixed it in his latest scripts
